language: java
jdk:
- oraclejdk8
sudo: enabled
git:
  depth: false
  submodules: false
cache:
  directories:
  - $HOME/.m2 # cache maven dependencies
branches:
  only:
  - master
  - /^release-.*$/
addons:
  sonarcloud:
    organization: "andre-lehnert-github" # the key of the org (https://sonarcloud.io/account/organizations)
    token:
      secure: $SONAR_CLOUD_KEY # travis ci environment variable with the sonar cloud token (https://sonarcloud.io/account/security/)
install: true
script:
- ls -l
- cd bogenliga # change to project directory
- mvn clean install # maven build with unit tests
- mvn cobertura:cobertura
- ls -l
- ../sonar-scanner # other script steps might be done before running the actual analysis
after_success:
- bash <(curl -s https://codecov.io/bash)




